// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: answer.sql

package sqlc

import (
	"context"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (
  text, question_id
) VALUES (
  $1, $2 
)
RETURNING id, question_id, text, created_at
`

type CreateAnswerParams struct {
	Text       string `json:"text"`
	QuestionID int64  `json:"question_id"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer, arg.Text, arg.QuestionID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM answers
WHERE id = $1
`

func (q *Queries) DeleteAnswer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnswer, id)
	return err
}

const getAnswer = `-- name: GetAnswer :one
SELECT id, question_id, text, created_at FROM answers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAnswer(ctx context.Context, id int64) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerByQuestion = `-- name: GetAnswerByQuestion :one
SELECT id, question_id, text, created_at FROM answers
WHERE question_id = $1 LIMIT 1
`

func (q *Queries) GetAnswerByQuestion(ctx context.Context, questionID int64) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByQuestion, questionID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listAnswers = `-- name: ListAnswers :many
SELECT id, question_id, text, created_at FROM answers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAnswersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAnswers(ctx context.Context, arg ListAnswersParams) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswer = `-- name: UpdateAnswer :one
UPDATE answers
  set text = $2
WHERE id = $1
RETURNING id, question_id, text, created_at
`

type UpdateAnswerParams struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, updateAnswer, arg.ID, arg.Text)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
